init_config:

instances:
- collect_container_size: false
  collect_exit_codes: false
  collect_images_stats: false
  collect_image_size: false
  collect_disk_stats: false
  collect_volume_count: false
  tags: []
  collect_events: true
  filtered_event_types: []
  capped_metrics: {}
