version: '3'
services:

  producer:
    image: lcarneirofreitas/producer-kafka
    network_mode: host

  consumer:
    image: lcarneirofreitas/consumer-kafka
    network_mode: host

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    network_mode: host
    environment:
      ZK_HOSTS: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
