version: '3'

services:
  producer:
    image: lcarneirofreitas/producer-kafka
    network_mode: host

  consumer:
    image: lcarneirofreitas/consumer-kafka
    network_mode: host

  kafka-manager:
    image: qnib/plain-kafka-manager
    network_mode: host
    environment:
      ZOOKEEPER_HOSTS: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      APPLICATION_SECRET: change_me_please
    restart: always

