version: '3'
services:

  datadog-agent:
    image: datadog/agent:latest
    environment:
      DD_API_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      DD_LOGS_ENABLED: 1
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: 1
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

  producer1:
    image: lcarneirofreitas/producer-kafka
    network_mode: host
    environment:
      BROKERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      TOPIC: "numtest"
      DELAY: "0.01"

  producer2:
    image: lcarneirofreitas/producer-kafka
    network_mode: host
    environment:
      BROKERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      TOPIC: "numtest"
      DELAY: "0.01"

  consumer1:
    image: lcarneirofreitas/consumer-kafka
    network_mode: host
    environment:
      BROKERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      TOPIC: "numtest"
      GROUPID: "mygroup"

  consumer2:
    image: lcarneirofreitas/consumer-kafka
    network_mode: host
    environment:
      BROKERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      TOPIC: "numtest"
      GROUPID: "mygroup"

  consumer3:
    image: lcarneirofreitas/consumer-kafka
    network_mode: host
    environment:
      BROKERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      TOPIC: "numtest"
      GROUPID: "mygroup"

  consumer4:
    image: lcarneirofreitas/consumer-kafka
    network_mode: host
    environment:
      BROKERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      TOPIC: "numtest"
      GROUPID: "mygroup"

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    network_mode: host
    environment:
      ZK_HOSTS: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
