---

- hosts: 127.0.0.1
  connection: local
  become: yes

  vars:
    path_tasks: /home/ubuntu/ansible

  tasks:

    - name: Init Ubuntu
      import_tasks: "{{ path_tasks }}/tasks/init-ubuntu.yml"

    - name: Install datadog agent
      import_tasks: "{{ path_tasks }}/tasks/datadog-agent.yml"

    - name: Install kafka cluster
      import_tasks: "{{ path_tasks }}/tasks/kafka-node.yml"

    - name: Running testinfra
      import_tasks: "{{ path_tasks }}/tasks/kafka-test.yml"