#!/bin/bash
#/etc/init.d/zookeeper

# Load environments zookeeper
if [ -f "/etc/default/zookeeper" ]; then
        . /etc/default/zookeeper
        export ZOOKEEPER_PATH="${ZOOKEEPER_PATH}"
        export ZOOKEEPER_CONF="${ZOOKEEPER_CONF}"
        export DAEMON_NAME="${DAEMON_NAME}"
        export ZOOKEEPER_HEAP_OPTS="${ZOOKEEPER_HEAP_OPTS}"
        export ZOOKEEPER_LOG4J_OPTS="${ZOOKEEPER_LOG4J_OPTS}"
        export LOG_DIR="${LOG_DIR}"
        export JMX_PORT="${JMX_PORT}"
else
        echo "File /etc/default/zookeeper does not exist."
        exit 1
fi

PATH=$PATH:$ZOOKEEPER_PATH

# See how we were called.
case "$1" in
  start)
        # Start daemon.
        pid=`ps ax | grep -i 'org.apache.zookeeper' | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]
          then
            echo "Zookeeper is already running";
        else
          echo "Starting $DAEMON_NAME";
          $ZOOKEEPER_PATH/bin/zookeeper-server-start.sh -daemon $ZOOKEEPER_CONF/zookeeper.properties
        fi
        ;;
  stop)
        echo "Shutting down $DAEMON_NAME";
        $ZOOKEEPER_PATH/bin/zookeeper-server-stop.sh
        ;;
  restart)
        $0 stop
        sleep 2
        $0 start
        ;;
  status)
        pid=`ps ax | grep -i 'org.apache.zookeeper' | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]
          then
          echo "Zookeeper is Running as PID: $pid"
        else
          echo "Zookeeper is not Running"
        fi
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
