# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  required_plugins = %w( vagrant-vbguest vagrant-disksize )
  _retry = false
  required_plugins.each do |plugin|
      unless Vagrant.has_plugin? plugin
          system "vagrant plugin install #{plugin}"
          _retry=true
      end
  end

  if (_retry)
      exec "vagrant " + ARGV.join(' ')
  end

  config.vm.box = 'ubuntu/xenial64'
  config.disksize.size = "10GB"
  hostname = 'kafka2'

  config.vm.network :private_network, ip: '192.168.33.51'

  config.vm.define hostname.to_sym do |box|
    box.vm.hostname = hostname

    box.vm.provider 'virtualbox' do |vb|
      vb.memory = '2048'
      vb.cpus = '2'
      vb.name = hostname
    end
  end
  config.vm.provision "shell", path: "bootstrap.sh"
end
